Первая альфа версия
lardc/hw-IGTUControlBoard pull request #1
Opened 2022-11-16 10:36 UTC by eugene-frost

2022-11-28 13:37 UTC, asytyi requested changes
Общие замечания:
1. Попадаются закомментированные участки кода, надо их убирать
2. По структуре проекта DebugActions.c и Diagnostic.c дублируют друг друга. Надо оставить что-то одно
3. ExternalDAC.c можно закинуть в LowLevel.c
4. А вот Controller.c выглядит перегруженным. Хочется часть функций логики верхнего уровня вынести в отдельную библиотеку Logic.c

2022-11-28 13:37 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
>  }
В целом перед запуском формирования есть смысл сбрасывать все EP и выходные значения общей функцией
`CONTROL_ResetOutputRegisters`

2022-11-28 13:37 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +			REGULATOR_VGS_FormUpdate(&RegulatorParams);
Не везде соблюдаются правила форматирования кода.
Надо в TrueSTUDIO добавить правило форматирования `d:\proton\Documents\Software\Code style\LARDC.xml` через меню Project->Properties как на [скрине ](https://snipboard.io/Gw2xdT.jpg)

После этого можно форматировать или участки кода через Ctrl+Shift+F, или весь через правый клик Source->Format

2022-11-28 13:37 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +		DataTable[REG_VGS] = 0;
Здесь и далее по коду: Если результат валиден, то надо так же в регистре 197 выставлять флаг `OPRESULT_OK`. Если результат невалиден, но при этом блок исправен (не зафэйлился), то надо выставлять `OPRESULT_FAIL` и через регистр 196 указывать код проблемы.

2022-11-28 13:37 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
>  		float Result;
Если инкрементировать объявленную переменную, то для исключения неоднозначного поведения лучше её явно обнулить

2022-11-28 13:37 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +	float Result = Regulator->VSenForm[Regulator->ConstantVFirstPulse];
Не уверен, что в данном контексте стоит использовать Pulse в названиях переменных. Здесь же речь не о массиве импульсов, а о массиве точек? Читается неоднозначно

2022-11-28 13:37 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +	if (Result > 0)
Если в результате пересчёта и корректировок результирующее значение станет меньше 0, то это не повод выдавать ворнинг. Можно просто обрезать всё что ниже 0

2022-11-28 13:37 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +		if ((CU_C_ADCCToX(MEASURE_C_CSenRaw[i]) > (0.3 * DataTable[REG_QG_C_SET])) && (CONTROL_C_Start_Counter == 0))
Магические константы лучше вынести через дефайны в начало файла или в Global.h

2022-11-28 13:37 UTC, asytyi commented on Firmware/Source/Controller/ConvertUtils.c
> +	return (Int16U)(((Value - C_VCutoffToExtDACParams.P0) / C_VCutoffToExtDACParams.P1) * C_VCutoffToExtDACParams.K);
Надо добавить общие функции, чтобы передавать параметры пересчёта как аргументы. Чтобы не было копипасты самих расчётных формул. Например так:
```
float CU_PotADCToV(Int16U Data)
{
	return CU_PotADCVToX(&V_AdcToVSenParamss, Data);
}

float CU_PotADCVToX(ConvertParams *Params, Int16U Data)
{
	float Value = Data * Params->K;
	return (Value * Value * Params->P2 + Value * Params->P1 + Params->P0);
}
//-----------------------------
```

При этом функция `float CU_PotADCVToX(ConvertParams *Params, Int16U Data)` объявляется в файле *.c, т.к. она имеет локальную применимость, и не торчит наружу в файле *,h

2022-11-28 13:37 UTC, asytyi commented on Firmware/Source/Controller/DebugActions.c
> +	DataTable[REG_DBG] == 0 ? LL_V_ShortOut(false) : LL_V_ShortOut(true);
Хитро через тернарный оператор) Можно же просто `LL_V_ShortOut(DataTable[REG_DBG])`

2022-11-28 13:37 UTC, asytyi commented on Firmware/Source/Controller/DebugActions.c
> +
Если во фрагменте кода нет объявления переменных, то фигурные скобки можно опустить. Код будет компактнее:
```
		case ACT_DBG_V_V_SET:
			if(CONTROL_State == DS_None)
				DBGACT_V_VSet();
			else
				*pUserError = ERR_OPERATION_BLOCKED;
			break;
```

2022-11-28 13:37 UTC, asytyi commented on Firmware/Source/Controller/LowLevel.c
> +void LL_V_CoefCSens(Int16U Data) // 0 - Low current, 1 - High current
Форматирование

2022-11-28 13:37 UTC, asytyi commented on Firmware/Source/Controller/Measurement.c
> +	Int16U result = ADC_Measure(ADC3, ADC3_POT_CHANNEL);
М?
```
Int16U MEASURE_V_VSen()
{
	return ADC_Measure(ADC1, ADC1_V_V_SEN_CHANNEL);
}
//-----------------------------------------------
```

2022-11-28 13:37 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +void CONTROL_V_HighPriorityProcess()
Вопрос по реализации тактирования регулятора. Сейчас получается, что по таймеру дёргается функция, в которой происходит программный запуск оцифровки и последующая обработка результата регулятором.
Предлагаю рассмотреть реализацию, когда по таймеру запускается оцифровка по DMA. А прерывание завершения записи в DMA дёргает функцию регулятора. Это уберёт ненужное ожидание завершения программной оцифровки, позволит делать усреднение.

2022-11-28 13:37 UTC, asytyi commented on Firmware/Source/Platform/DeviceObjectDictionary.h
> +#define REG_ADC_C_C_SEN_P0				22	// Смещение тонкой подстройки Р0
Здесь и далее: Т.к. регистры флоатовские, то в них можно сразу писать дробные числа. Умножения/деления на 1000, 1е6 и т.п. можно убрать

2022-12-12 14:45 UTC, eugene-frost commented on Firmware/Source/Controller/Controller.c
>  }
+

2022-12-12 15:22 UTC, eugene-frost commented on Firmware/Source/Controller/Controller.c
> +		DataTable[REG_VGS] = 0;
То есть регистры результата и проблемы относятся только к операциям, и всегда в связке друг с другом?
То есть если CurrentNotReached - это будет `OPRESULT_OK = false; PROBLEM = CurrentNotReached` ?

А логика Fault, Disable и Warning какая тогда?

2022-12-13 07:51 UTC, eugene-frost commented on Firmware/Source/Controller/Controller.c
> +	float Result = Regulator->VSenForm[Regulator->ConstantVFirstPulse];
Да, неочевидно. Заменил на Step, т.к. это по сути шаг регулятора, на котором происходит то или иное событие. Он же - порядковый номер элемента в массивах.

2022-12-13 07:56 UTC, eugene-frost commented on Firmware/Source/Controller/Controller.c
> +	if (Result > 0)
Отрицательный измеренный ток утечки разве не говорит о том, что имеется какая-то ошибка (например, в коммутации или в считывании значения из PAU)? Не совсем понял, какое состояние у блока должно быть при отрицательном значении?

2022-12-13 12:35 UTC, eugene-frost commented
Саш, по п.2. `По структуре проекта DebugActions.c и Diagnostic.c дублируют друг друга. Надо оставить что-то одно`
Я предполагал в DebugActions.c вынести всё низкоуровневое - типа щелкнуть реле и т.п. для первичной проверки хардвара платы + какую-то совсем простую логику типа сгенерить импульс напряжения на выходе ЦАП длительностью 1мс.
А в Diagnostic.c будет вся логика самодиагностики платы, чтоб можно было диагностику запустить и командой и автоматически изнутри Controller.c, при команде Enable например.

2022-12-16 09:28 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +		DataTable[REG_VGS] = 0;
По Problem всё верно.
Fault - внутренний сбой в блоке, не позволяющий продолжить измерение. Например ожидание заряда конденсаторной батареи
Disable - то же самое, что Fault, но без возможности программного сброса. Только перезапуск по питанию.
Warning - некое предупреждение, возникшее в ходе измерения, но не влияющее на его результат.

Чаще всего в практике используются Problem, т.к. они как правило обусловлены факторами, связанными с подключением прибора. Например, подали управление, хотим пустить ток в силовой цепи, а ток не идёт.
И чуть реже Fault. Disable и Warning давно не было случая применить.

2022-12-16 09:30 UTC, asytyi commented
По п.2 ок, можно и так

2022-12-22 13:04 UTC, eugene-frost commented on Firmware/Source/Controller/Controller.c
> +	if (Result > 0)
@asytyi по логике Opresult/Problem в этой ситуации должно быть что-то такое? : `OPRESULT_OK = false; PROBLEM = NegativeCurrent`

2022-12-26 12:29 UTC, eugene-frost commented on Firmware/Source/Controller/Controller.c
> +void CONTROL_V_HighPriorityProcess()
@asytyi Идею понял, повертел, как это лучше реализовать, но пока предлагаю в первой версии отставить как есть, по той причине, что у блока в обычном рабочем режиме U сенсится с потенциальных линий, а в дебаге и режиме самотестирования с внутренних цепей. И сейчас это достаточно просто будет переключать - сенсить с одного АЦП или с другого, а ДМА надо будет перенастраивать в зависимости от режима заранее, что чуть сложнее.

2023-01-11 15:30 UTC, asytyi reviewed
Выглядит симпатично. Пару комментариев по моментам, за которые глаз зацепился.

2023-01-11 15:30 UTC, asytyi commented on Firmware/Source/Controller/Diagnostic.c
>  		case ACT_DIAG_VGS:
Эти диагностические функции ещё не реализовывались?

2023-01-11 15:30 UTC, asytyi commented on Firmware/Source/Controller/LowLevel.c
>  //
По поводу функции
```
void LL_OutMultiplex(bool State)	// true - Current, false - Voltage
{
	GPIO_SetState(GPIO_OUT_MULTIPLEX, !State);
}
```
Если хочется оставить комментарий, то скорее всего код недостаточно самодокументированный. Здесь лучше сделать обёртки, которые явно будут говорить о назначении, например:
```
void LL_OutMultiplexCurrent()
{
	GPIO_SetState(GPIO_OUT_MULTIPLEX, false);
}
```

2023-01-11 15:30 UTC, asytyi commented on Firmware/Source/Controller/LowLevel.c
> +	switch(Data)
Здесь, кстати, тоже лучше сделать обёртки для младшего и старшего диапазона. Тогда можно убрать селекторы диапазонов
```
#define LL_V_LOW_CURRENT_LIMIT		0	// 1 mA limit
#define LL_V_HIGH_CURRENT_LIMIT 	1	// 200 mA limit

#define LL_V_LOW_CURRENT_SENS_COEF	0	// 0 - 20 mA sensing
#define LL_V_HIGH_CURRENT_SENS_COEF	1	// 20 - 200 mA sensing
```
и в функции `CONTROL_VGS_StartProcess()` выбор диапазона будет выглядеть как
```
if(DataTable[REG_VGS_C_TRIG] <= DataTable[REG_V_C_SENS_THRESHOLD])
    LL_V_CoefCSensLowRange();
else
    LL_V_CoefCSensHighRange();
```

2023-01-11 15:30 UTC, asytyi commented on Firmware/Source/Controller/LowLevel.c
> +	switch(Data)
Здесь аналогично

2023-01-22 16:16 UTC, eugene-frost commented on Firmware/Source/Controller/Diagnostic.c
>  		case ACT_DIAG_VGS:
Реализовывались, выкатил в последнем коммите

2023-01-23 14:01 UTC, asytyi approved these changes

2023-01-23 14:01 UTC, asytyi commented on Firmware/Source/Controller/LowLevel.c
> +void LL_V_CoefCSensLowRange() {
Египетские скобки не используем

2023-01-23 14:01 UTC, asytyi commented on Firmware/Source/Controller/Diagnostic.c
> +				DataTable[REG_QG_C_THRESHOLD] = DIAG_REG_QG_C_THRESHOLD;
Строго говоря, не элегантной практикой является ситуация, когда блок сам переписывает значения во входных регистрах.  Хотя работать это будет, т.к. параметры будут задаваться верхним уровнем перед каждым измерением

2023-01-23 14:03 UTC, merged